import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";
import type { ReactNode } from "react";
import { cn } from "@/lib/utils";
import {TRPCReactProvider} from "@/trpc/react";
import {TooltipProvider} from "@/components/ui/tooltip";
import {Toaster} from "@/components/ui/sonner";
import ProvidersProvider from "@/components/dashboard/providers/ProvidersProvider";
import SourceProvider from "@/components/dashboard/inferenceSource/SourceProvider";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased dark",
        fontSans.variable
      )}>
      <TRPCReactProvider>
        <TooltipProvider>
          <ProvidersProvider>
            <SourceProvider>
              {children}
            </SourceProvider>
          </ProvidersProvider>
        </TooltipProvider>
      </TRPCReactProvider>
      <Toaster/>
      </body>
    </html>
  );
}
